// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proxy/reflex/config.proto

package reflex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flow          string                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_reflex_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

type Fallback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dest          uint32                 `protobuf:"varint,1,opt,name=dest,proto3" json:"dest,omitempty"`
	Xver          string                 `protobuf:"bytes,2,opt,name=xver,proto3" json:"xver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fallback) Reset() {
	*x = Fallback{}
	mi := &file_proxy_reflex_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fallback) ProtoMessage() {}

func (x *Fallback) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fallback.ProtoReflect.Descriptor instead.
func (*Fallback) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{1}
}

func (x *Fallback) GetDest() uint32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

func (x *Fallback) GetXver() string {
	if x != nil {
		return x.Xver
	}
	return ""
}

type InboundConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Clients         []*Account             `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Fallback        *Fallback              `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
	MorphingProfile string                 `protobuf:"bytes,3,opt,name=morphing_profile,json=morphingProfile,proto3" json:"morphing_profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InboundConfig) Reset() {
	*x = InboundConfig{}
	mi := &file_proxy_reflex_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundConfig) ProtoMessage() {}

func (x *InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundConfig.ProtoReflect.Descriptor instead.
func (*InboundConfig) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{2}
}

func (x *InboundConfig) GetClients() []*Account {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *InboundConfig) GetFallback() *Fallback {
	if x != nil {
		return x.Fallback
	}
	return nil
}

func (x *InboundConfig) GetMorphingProfile() string {
	if x != nil {
		return x.MorphingProfile
	}
	return ""
}

type OutboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Account             `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundConfig) Reset() {
	*x = OutboundConfig{}
	mi := &file_proxy_reflex_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundConfig) ProtoMessage() {}

func (x *OutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundConfig.ProtoReflect.Descriptor instead.
func (*OutboundConfig) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{3}
}

func (x *OutboundConfig) GetClients() []*Account {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *OutboundConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OutboundConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_proxy_reflex_config_proto protoreflect.FileDescriptor

const file_proxy_reflex_config_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/reflex/config.proto\x12\freflex.proxy\"-\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\tR\x04flow\"2\n" +
	"\bFallback\x12\x12\n" +
	"\x04dest\x18\x01 \x01(\rR\x04dest\x12\x12\n" +
	"\x04xver\x18\x02 \x01(\tR\x04xver\"\x9f\x01\n" +
	"\rInboundConfig\x12/\n" +
	"\aclients\x18\x01 \x03(\v2\x15.reflex.proxy.AccountR\aclients\x122\n" +
	"\bfallback\x18\x02 \x01(\v2\x16.reflex.proxy.FallbackR\bfallback\x12)\n" +
	"\x10morphing_profile\x18\x03 \x01(\tR\x0fmorphingProfile\"o\n" +
	"\x0eOutboundConfig\x12/\n" +
	"\aclients\x18\x01 \x03(\v2\x15.reflex.proxy.AccountR\aclients\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04portB(Z&github.com/xtls/xray-core/proxy/reflexb\x06proto3"

var (
	file_proxy_reflex_config_proto_rawDescOnce sync.Once
	file_proxy_reflex_config_proto_rawDescData []byte
)

func file_proxy_reflex_config_proto_rawDescGZIP() []byte {
	file_proxy_reflex_config_proto_rawDescOnce.Do(func() {
		file_proxy_reflex_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_reflex_config_proto_rawDesc), len(file_proxy_reflex_config_proto_rawDesc)))
	})
	return file_proxy_reflex_config_proto_rawDescData
}

var file_proxy_reflex_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_reflex_config_proto_goTypes = []any{
	(*Account)(nil),        // 0: reflex.proxy.Account
	(*Fallback)(nil),       // 1: reflex.proxy.Fallback
	(*InboundConfig)(nil),  // 2: reflex.proxy.InboundConfig
	(*OutboundConfig)(nil), // 3: reflex.proxy.OutboundConfig
}
var file_proxy_reflex_config_proto_depIdxs = []int32{
	0, // 0: reflex.proxy.InboundConfig.clients:type_name -> reflex.proxy.Account
	1, // 1: reflex.proxy.InboundConfig.fallback:type_name -> reflex.proxy.Fallback
	0, // 2: reflex.proxy.OutboundConfig.clients:type_name -> reflex.proxy.Account
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proxy_reflex_config_proto_init() }
func file_proxy_reflex_config_proto_init() {
	if File_proxy_reflex_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_reflex_config_proto_rawDesc), len(file_proxy_reflex_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_reflex_config_proto_goTypes,
		DependencyIndexes: file_proxy_reflex_config_proto_depIdxs,
		MessageInfos:      file_proxy_reflex_config_proto_msgTypes,
	}.Build()
	File_proxy_reflex_config_proto = out.File
	file_proxy_reflex_config_proto_goTypes = nil
	file_proxy_reflex_config_proto_depIdxs = nil
}
